import { expect, test } from "@playwright/test";

test("Meeting作成・参加者・Transcript編集・完了・XSS安全表示", async ({ page, context }) => {
 const token = process.env.E2E_SESSION_TOKEN;
 if (!token) throw new Error("E2E session fixture is missing");
 await page.goto("/login");
 await context.addCookies([{ name: "authjs.session-token", value: token, domain: "127.0.0.1", path: "/", httpOnly: true, sameSite: "Lax" }]);
 const organizations = await (await context.request.get("/api/organizations")).json();
 const projectResponse = await context.request.post("/api/projects", { headers: { origin: "http://127.0.0.1:3100" }, data: { name: "Meeting E2E Project", organizationId: organizations.data.find((row: {name: string}) => row.name === "Organization A").id } });
 expect(projectResponse.status()).toBe(201); const project = (await projectResponse.json()).data;
 await page.goto(`/projects/${project.id}`);
 await page.getByRole("link", { name: "会議一覧", exact: true }).click();
 await expect(page.getByText("まだ会議がありません", { exact: false })).toBeVisible();
 await page.getByRole("link", { name: "会議を作成", exact: true }).click();
 await page.getByLabel("会議名", { exact: true }).fill("週次会議E2E");
 await page.getByLabel("開催日時（日本時間）", { exact: true }).fill("2026-09-16T10:00:12.345");
 await page.getByRole("button", { name: "会議を作成", exact: true }).click();
 await expect(page.getByRole("heading", { name: "週次会議E2E", exact: true })).toBeVisible();
 const meetingUrl = page.url(); const meetingId = meetingUrl.split("/").at(-1)!;
 await expect(page.getByText("Owner A · host", { exact: false })).toBeVisible();
 await page.getByText("会議情報を編集", { exact: true }).click();
 const editMeeting = page.getByRole("form", { name: "会議を保存", exact: true });
 await editMeeting.getByLabel("会議名", { exact: true }).fill("更新済み週次会議E2E");
 await editMeeting.getByRole("button", { name: "会議を保存", exact: true }).click();
 await expect(page.getByRole("heading", { name: "更新済み週次会議E2E", exact: true })).toBeVisible();
 const storedMeeting = await (await context.request.get(`/api/meetings/${meetingId}`)).json();
 expect(storedMeeting.data.meetingDate).toBe("2026-09-16T01:00:12.345Z");
 const addParticipant = page.getByRole("form", { name: "参加者を追加", exact: true });
 await addParticipant.getByLabel("表示名", { exact: true }).fill("外部ゲスト");
 await addParticipant.getByRole("button", { name: "参加者を追加", exact: true }).click();
 await expect(page.getByText("外部ゲスト · participant", { exact: false })).toBeVisible();
 await page.getByRole("button", { name: "自分の参加を記録", exact: true }).click();
 const addTranscript = page.getByRole("form", { name: "文字起こしを追加", exact: true });
 await addTranscript.getByLabel("話者名", { exact: true }).fill("外部ゲスト");
 await addTranscript.getByLabel("開始秒", { exact: true }).fill("12.2");
 await addTranscript.getByLabel("終了秒", { exact: true }).fill("18.7");
 const payload = "<script>window.meetingXss=true</script>";
 await addTranscript.getByLabel("発言本文", { exact: true }).fill(payload);
 await addTranscript.getByRole("button", { name: "文字起こしを追加", exact: true }).click();
 await expect(page.locator("p.user-content").filter({ hasText: payload })).toBeVisible();
 expect(await page.evaluate(() => Object.hasOwn(window, "meetingXss"))).toBe(false);
 await expect(page.getByText("00:00:12 外部ゲスト", { exact: false })).toBeVisible();
 await page.getByText("発言を編集: 1", { exact: true }).click();
 const editTranscript = page.getByRole("form", { name: "文字起こしを保存", exact: true });
 await editTranscript.getByLabel("発言本文", { exact: true }).fill("API仕様を金曜日までに更新します。");
 await editTranscript.getByRole("button", { name: "文字起こしを保存", exact: true }).click();
 await expect(page.locator("p.user-content").filter({ hasText: "API仕様を金曜日までに更新します。" })).toBeVisible();
 await page.getByRole("button", { name: "会議を開始", exact: true }).click();
 await expect(page.getByText("状態: recording", { exact: false })).toBeVisible();
 await page.getByRole("button", { name: "処理へ進む", exact: true }).click();
 await expect(page.getByText("状態: processing", { exact: false })).toBeVisible();
 await expect(page.getByRole("button", { name: "文字起こしを追加", exact: true })).toHaveCount(0);
 await page.getByRole("button", { name: "会議を完了", exact: true }).click();
 await expect(page.getByText("状態: completed", { exact: false })).toBeVisible();
 await page.reload();
 await expect(page.getByText("状態: completed", { exact: false })).toBeVisible();
 const denied = await context.request.post(`/api/meetings/${meetingId}/transcripts`, { headers: { origin: "http://127.0.0.1:3100" }, data: { speakerName: "late", startedAt: 0, text: "late", sequenceNo: 2 } });
 expect(denied.status()).toBe(409);
});
