import { expect, test } from "@playwright/test";
test("Organization作成からProject編集・archive・空Organization削除まで", async ({ page, context }) => {
  const token = process.env.E2E_SESSION_TOKEN;
  if (!token) throw new Error("E2E session fixture is missing");
  await page.goto("/login");
  await context.addCookies([{ name: "authjs.session-token", value: token, domain: "127.0.0.1", path: "/", httpOnly: true, sameSite: "Lax" }]);
  await page.goto("/organizations");
  await page.getByRole("link", { name: "組織を作成", exact: true }).click();
  await page.getByLabel("組織名", { exact: true }).fill("E2E組織");
  await page.getByRole("button", { name: "作成", exact: true }).click();
  await expect(page.getByRole("heading", { name: "E2E組織", exact: true })).toBeVisible();
  const organizationUrl = page.url();
  await page.getByRole("link", { name: "プロジェクトを作成", exact: true }).click();
  await page.getByLabel("プロジェクト名").fill("E2Eプロジェクト");
  await page.getByLabel("説明").fill("作成時の説明");
  await page.getByRole("button", { name: "作成", exact: true }).click();
  await expect(page.getByRole("heading", { name: "E2Eプロジェクト", exact: true })).toBeVisible();
  const projectUrl = page.url();
  await page.getByLabel("プロジェクト名").fill("更新したプロジェクト");
  await page.getByRole("button", { name: "保存", exact: true }).click();
  await expect(page.getByRole("heading", { name: "更新したプロジェクト", exact: true })).toBeVisible();
  page.on("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "アーカイブ", exact: true }).click();
  await expect(page).toHaveURL(/\/projects$/);
  await page.goto(projectUrl);
  await expect(page.getByText("状態: archived", { exact: false })).toBeVisible();
  await page.goto(organizationUrl);
  await page.getByRole("button", { name: "組織を削除", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("プロジェクトが存在する組織は削除できません");
  await page.goto("/organizations/new");
  await page.getByLabel("組織名", { exact: true }).fill("空の組織");
  await page.getByRole("button", { name: "作成", exact: true }).click();
  await expect(page.getByRole("heading", { name: "空の組織", exact: true })).toBeVisible();
  const deletedUrl = page.url();
  await page.getByRole("button", { name: "組織を削除", exact: true }).click();
  await expect(page).toHaveURL(/\/organizations$/);
  await page.goto(deletedUrl);
  await expect(page.getByRole("heading", { name: "404 対象が見つかりません" })).toBeVisible();
});
