import { expect, test } from "@playwright/test";
test("Approved Minutes → Candidate generation → detail/edit/approve/reject → regeneration", async ({ page, context }) => {
 const token = process.env.E2E_SESSION_TOKEN; if (!token) throw new Error("Missing test session");
 await context.addCookies([{ name: "authjs.session-token", value: token, domain: "127.0.0.1", path: "/", httpOnly: true, sameSite: "Lax" }]);
 const headers = { origin: "http://127.0.0.1:3100" }; const organizations = (await (await context.request.get("/api/organizations")).json()).data; const organizationId = organizations.find((o: { name: string }) => o.name === "Organization A").id;
 const project = (await (await context.request.post("/api/projects", { headers, data: { name: "Candidate E2E", organizationId } })).json()).data;
 const meeting = (await (await context.request.post(`/api/projects/${project.id}/meetings`, { headers, data: { title: "候補生成会議", meetingDate: "2026-09-16T01:00:00Z" } })).json()).data;
 expect((await context.request.post(`/api/meetings/${meeting.id}/transcripts`, { headers, data: { speakerName: "発言者", startedAt: 12, endedAt: 18, text: "API仕様を確認して更新する。", sequenceNo: 1 } })).status()).toBe(201);
 await page.goto(`/meetings/${meeting.id}/minutes`); await page.getByRole("button", { name: "AI議事録を生成", exact: true }).click(); await expect(page.getByRole("heading", { name: "Version 1 · review" })).toBeVisible(); await page.getByRole("button", { name: "内容を確認して承認" }).click(); await expect(page.getByRole("heading", { name: "Version 1 · approved" })).toBeVisible();
 await page.getByRole("link", { name: "AIチケット候補を確認" }).click(); await expect(page.getByText("AIチケット候補はまだありません", { exact: false })).toBeVisible(); await page.getByRole("button", { name: "AIチケット候補を生成", exact: true }).click(); await expect(page.getByText("2件の候補", { exact: true })).toBeVisible();
 await page.getByRole("link", { name: "API仕様を更新する", exact: true }).click(); await expect(page.getByRole("heading", { name: "チケット候補の確認" })).toBeVisible(); const detailUrl = page.url();
 await page.getByRole("link", { name: /発言を確認/ }).click(); await expect(page.locator("li:target")).toContainText("API仕様を確認して更新する。"); await page.goto(detailUrl);
 await page.getByLabel("タイトル", { exact: true }).fill("人が修正したAPI仕様更新"); const xss = "<script>window.candidateXss=true</script>"; await page.getByLabel("説明", { exact: true }).fill(xss); await page.getByLabel("優先度", { exact: true }).selectOption("high"); await expect(page.getByRole("button", { name: "承認", exact: true })).toBeDisabled(); await page.getByRole("button", { name: "候補を保存" }).click(); await expect(page.getByRole("button", { name: "承認", exact: true })).toBeEnabled(); await page.getByRole("button", { name: "承認", exact: true }).click(); await expect(page.getByText("状態: 承認済み候補", { exact: true })).toBeVisible(); await expect(page.getByLabel("タイトル", { exact: true })).toBeDisabled(); expect(await page.evaluate(() => Object.hasOwn(window, "candidateXss"))).toBe(false);
 await page.getByRole("link", { name: "候補一覧へ" }).click(); const second = page.getByRole("article", { name: "API仕様を確認する", exact: true }); await second.getByRole("button", { name: "却下", exact: true }).click(); await expect(second.getByText("状態: 却下済み候補", { exact: true })).toBeVisible();
 await page.getByRole("link", { name: "却下済み", exact: true }).click(); await expect(page.getByText("1件の候補", { exact: true })).toBeVisible(); await page.getByRole("link", { name: "すべて", exact: true }).click(); await page.getByRole("button", { name: "チケット候補を再生成", exact: true }).click(); await expect(page.getByText("4件の候補", { exact: true })).toBeVisible(); await expect(page.getByText("状態: 承認済み候補", { exact: true })).toBeVisible();
 const tickets = await (await context.request.get(`/api/projects/${project.id}/tickets`)).json(); expect(tickets.data).toEqual([]);
});
